/*
 * Album Store API
 * CS6650 Fall 2023
 *
 * OpenAPI spec version: 1.1
 * Contact: i.gorton@northeasern.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ErrorMsg;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LikeApi
 */
@Ignore
public class LikeApiTest {

    private final LikeApi api = new LikeApi();

    /**
     * 
     *
     * like or dislike album
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void reviewTest() throws Exception {
        String likeornot = null;
        String albumID = null;
        api.review(likeornot, albumID);

        // TODO: test validations
    }
}
